env:
  es2021: true
  node: true
  mocha: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_$'
      argsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
  space-before-function-paren:
    - error
    - anonymous: always
      asyncArrow: always
      named: never
