version: '3'
services:
  redis:
    # https://hub.docker.com/_/redis
    image: docker.io/library/redis:7-alpine
    ports:
      - '6379:6379'

  mongodb:
    # https://hub.docker.com/_/mongo
    image: docker.io/library/mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  postgres:
    # https://hub.docker.com/_/postgres
    image: docker.io/library/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example

  # mariadb:
  #   # https://hub.docker.com/_/mariadb
  #   image: docker.io/library/mariadb:11.1
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=example

networks:
  hostnet:
    external: true
    name: host
